# Use an official Node.js runtime as a parent image
FROM node:20

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install any needed packages
RUN npm install

# Bundle app source
COPY . .

# Expose the port the app runs on
EXPOSE 5173

# Define the command to run your app with host binding for Docker
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
