# Docker Compose file to run PostgreSQL database for local development
# This allows you to quickly spin up a database without installing PostgreSQL directly

# Version of the Docker Compose file format (optional in newer versions)
version: '3.8'

# Services define the containers that will be created
services:
  # Name of this service (you can reference it as "db" from other containers)
  db:
    # The Docker image to use (official PostgreSQL image from Docker Hub)
    image: postgres:15
    
    # Always restart the container if it stops (useful for development)
    restart: always
    
    # Environment variables to configure the PostgreSQL instance
    environment:
      # The PostgreSQL superuser name
      POSTGRES_USER: user
      
      # The PostgreSQL superuser password
      POSTGRES_PASSWORD: password
      
      # The name of the default database to create
      POSTGRES_DB: yultimate_db
    
    # Port mapping: exposes the container's port 5432 to your host's port 5432
    # Format: "HOST_PORT:CONTAINER_PORT"
    # This allows your backend to connect to PostgreSQL at localhost:5432
    ports:
      - "5432:5432"
    
    # Volumes persist data even when the container is stopped/removed
    # This prevents data loss when you restart the container
    volumes:
      # Maps a named volume "postgres_data" to the container's data directory
      - postgres_data:/var/lib/postgresql/data

# Named volumes are defined here
volumes:
  # This volume stores the PostgreSQL data files
  postgres_data:
